language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack:
    secure: "x1XGXJaglp86r9ES9QYHtyWHFeSAd1IrFTdvJr8HHQwZfmfPFvv2LwUTRpz6JiFJJQ7efU+YnQ33Bn/1NBJQkwy05ujZYuWuTtwTEIzlWQGsZelqAeaMjreDL50bGEzkvX6MNfm2N7bWJAcEQVYcZHJ5y33QwlJNT42uza202reEeHpPlEJQDgyCNCzYC6wMUqaI8fEfVvZZgk4VXAKccZyB/MMRs1NYOg2RMsiiXWK0z+dY8YaWHVH8CklMeN/Z8JZLT46TdJM2EdvrEbNWPNZeNDYfoDYYRrdX0n3WOmXEVvmEGa0ltn6HXcfqLbPzokBuY1yxxiI8Oz5VvdGFs+zoq0ew3qg1ybDuiG8nx4EOf6naVK1x4yescO3DD9CBdNTC8X9I1eix2h+aVLMyzeoKdPhC9Pp0FN9NXxmXLZo0YgXnrXi2/rpsO6mcxT5wOBkLMR9a4nGua5zEe19Aer9LnoJgz0qSOKmqyeLmgz9NN12cRhcGxj7e5DYYr1O3Xgn8woPGsw0TluBrzNFiKOPCsYVNDsNhkupyFrQ31+qbsGK31diHcyhdRtg002uPuxZybZPio2Dcp3PcOXBgUGel60TYdqx7pXwwMlEeVJNtVahRN+WAjt60d6WUdUNh9hi0dKduUrjaBw4gt/ZR1I+JU/5S+0jhKHdfI56/VKA="
  email:
    recipients:
      - mirichi5597@hotmail.com
      - miriamnavamucino@gmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "CxfRJMVGzRx+5LZ1P1rvKO0sc3o3dXofZQaTLeIU8HPnwWnlCa8wkeos7kwo7cIMXALc9TiJaFg5qxHjSYWjAV+V+2XKIXQYNM3gcua4QIFNBKlWYMicmY79EPledrsXZeckxgxhMKJJAyojmzo4BBZyTHb5vo2UayH41MG139vgPaJHOKgP9K/QmLgpwhvtG52jLXVWI/wqaLSvO8UJMK3E8ErjD0AxvPohIU5bYvZaAIrQzq0BoBIVXXaNgF7unbMZNCaZoTZlC2kLTldCO7bHzcM+rcbo2+FH/DLAtNhFgiajZKFgqSMt1HWHABhrn+VFC0xNYkY89I8JJQCcepAek92JRb4sdQUpTHzq7bHDGnx6HUMiXuyphuirrYbRhghIFUY7lE72Cke+J8DhtN6Hh6NDLrdyCsFMUu7wWaBjAhIqaISeaxuGF9ZOKr6b4kKCNqql4dO+W3rXNaudBwdP+XIJyykcjXuGUUPCpMeIsKrmB9XHUzGVR97uHKdzrWipJ3C2NxVV2uH5ZiVEF1GbFIaJ7w0C5mMKuVj1mtdjlJmieQyFEj4ImetY6tNUbUyz+LRRz6bk9Aeu9M0IFRRAU/sGjCiVsylxY8W1Ru3n3bKyhwtLaO2FMDanuvdMYaZFkf8fk5hOtqJyXYVkpHaBZjDyas8qtRqVnnWbk44="
  app: platzi-store-backend-mnm
  on:
    repo:  MiriamNM/platzi-store-backend